Add a workflow to lint with clang-tidy
libtql/tqlib pull request #21
Opened 2022-01-27 12:49 UTC by umutoztunc

2022-01-27 14:29 UTC, liangjs requested changes
I tested it [here](https://github.com/liangjs/tqlib/runs/4967450220?check_suite_focus=true) and got some errors. Besides, it didn't put review comments on the test [PR](https://github.com/liangjs/tqlib/pull/3).

Let's fix them!

2022-01-27 17:35 UTC, umutoztunc commented
I am not sure why it did not put review comments on your PR. I tried to fix it by adding the if statement to exit with return code 1 when the it has comments, maybe this fixes its behaviour since I took it from its author's example.

2022-01-31 07:12 UTC, liangjs commented
Our code needs LLVM version 12 at least, but the newest version provided by clang-tidy-review is 11. Maybe we can install version 12 and run clang-tidy commands by ourselves?

Missing review comments may not be an essential issue, because we can still check the results manually.

2022-01-31 20:27 UTC, umutoztunc commented
`clang-tidy-review` action now supports `clang-tidy-12`:
https://github.com/ZedThree/clang-tidy-review/commit/b1c225a69046d1ec35d0bbde65098d7dd57a3d8e

I think we can merge this PR now. However, I am not sure if we should `exit 1` when there are comments from `clang-tidy` or not.

2022-02-01 04:34 UTC, liangjs requested changes

2022-02-01 04:34 UTC, liangjs commented on .github/workflows/clang-tidy.yaml
> +        uses: ZedThree/clang-tidy-review@v0.7.1
We may need to change the version `v0.7.1`, because we want to use the clang-tidy-12 which is supported in a very recent commit of clang-tidy-review.

2022-02-01 04:34 UTC, liangjs commented on .github/workflows/clang-tidy.yaml
> +          build_dir: out
Recently clang-tidy-review supports specifying a `.clang-tidy` config file, and its default location is empty. I think we need to use this feature to make sure it uses our custom config file.
https://github.com/ZedThree/clang-tidy-review/commit/0ad0fe152ac38306c2a987a861593354208bb6ab

2022-02-15 13:51 UTC, liangjs reviewed
LGTM. But it is weird that I still get compile errors.

https://github.com/liangjs/tqlib/runs/5200981382?check_suite_focus=true

```
/github/workspace/number_theory/sieve.h:38:14: error: no member named 'bit_width' in namespace 'std' [clang-diagnostic-error]
```

2022-02-15 14:56 UTC, liangjs commented
> LGTM. But it is weird that I still get compile errors.
> 
> https://github.com/liangjs/tqlib/runs/5200981382?check_suite_focus=true
> 
> ```
> /github/workspace/number_theory/sieve.h:38:14: error: no member named 'bit_width' in namespace 'std' [clang-diagnostic-error]
> ```

I tested it in docker. Installing g++-10 will solve this.

2022-02-15 17:03 UTC, umutoztunc commented
I have added `g++-10`, can you please test it again?

2022-02-16 01:12 UTC, liangjs commented
I got an error.

```
Invalid workflow file: .github/workflows/clang-tidy.yaml#L15
The workflow is not valid. .github/workflows/clang-tidy.yaml (Line: 15, Col: 25): A sequence was not expected
```

The related code is [here](https://github.com/ZedThree/clang-tidy-review/blob/809e36703751a8800bd5e206234e2f367171f588/review.py#L790-L792). So maybe only `apt_packages: libgtest-dev,g++10` without brackets and spaces works.

2022-02-16 09:40 UTC, umutoztunc commented
It seems following your advice worked out here.

2022-02-16 10:35 UTC, liangjs approved these changes
This is so nice!

2022-02-16 10:36 UTC, merged